name: doctor_ack
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  internet_connection_checker: ^1.0.0+1
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  awesome_dialog: ^3.2.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  animate_do: ^3.3.3
  flutter_rating_bar: ^4.0.1
  arabic_numbers: ^1.0.0
  carousel_slider: ^5.0.0
  http: ^1.2.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  url_launcher: ^6.2.4
  pinput: ^5.0.0
  webview_flutter: ^4.5.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.8.4
  lottie: ^3.0.0
  intl: ^0.19.0
  custom_radio_grouped_button: ^2.2.1
  maps_launcher: ^2.2.0
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_stripe: ^10.0.0
  flutter_dotenv: ^5.1.0
  image_picker: ^1.0.7
  syncfusion_flutter_calendar: ^26.2.14
  syncfusion_flutter_charts: ^26.2.14
  dropdown_button2: ^2.3.9
  syncfusion_flutter_datagrid: ^26.2.14
  easy_localization: ^3.0.3
  readmore: ^3.0.0
  easy_date_timeline: ^1.0.2
  syncfusion_flutter_datepicker: ^26.2.14
  speech_to_text: ^6.6.0
  share_plus: ^10.1.1
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_pdfviewer: ^26.2.14
  # firebase_core: ^3.6.0
  # firebase_dynamic_links: ^6.0.3
  # firebase_messaging: ^15.0.3
  # flutter_local_notifications: ^17.2.1+2
  fluttertoast: ^8.2.4
  permission_handler: ^11.2.1
  # swipeable_page_route: ^0.4.2
  sqflite: ^2.3.2
  map_launcher: ^3.1.0
  device_preview: ^1.1.0
  syncfusion_flutter_core: ^26.2.5

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_icon1.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo.png"
  android: true
  ios: true

  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#FFFFFF"

flutter:

  uses-material-design: true

  assets:
    - assets/.env
    - assets/images/
    - assets/images/logo.png
    #    - assets/icons/
    - assets/iconsN/
    - assets/languages/
    - assets/lottie/

  fonts:
    - family: Quentin
      fonts:
        - asset: assets/fonts/Quentin.ttf

    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf